# Setup
title:               Allen Lee's blog
tagline:             'Programmer turned cancer fighter'
description:         'Personal blog of programmer and cancer survivor Allen Lee. '
url:                 http://allenlee.net
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Allen Lee
  url:               allenlee.net
  email:             al@allenlee.net

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
